version: '3.8'
services:
    mysql:
        container_name: db
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - database:/var/lib/mysql

    joomla:
        depends_on:
            - mysql
        image: joomla:4.0.4-php7.4-apache
        container_name: joomla
        ports:
            - 8080:80
        environment:
            - JOOMLA_DB_HOST=mysql
            - JOOMLA_DB_PASSWORD=db_password
            - JOOMLA_DB_NAME=webserver
            - JOOMLA_DB_USER=root
        networks:
            - web
        volumes:
            - joomla:/var/www/html

networks:
  web:
    driver: bridge
volumes:
  joomla:
  database:
