version: '3.1'

services:
  joomla:
    depends_on:
      - mysql
    image: joomla:4.0.4-php7.4-apache
    container_name: jl
    ports:
      - 8080:80
    environment:
      - JOOMLA_DB_HOST=mysql
      - JOOMLA_DB_PASSWORD=db_password
      - JOOMLA_DB_NAME=joomla_ws
      - JOOMLA_DB_USER=root
    networks:
      - web
    volumes:
      - joomla:/var/www/html

  mysql:
    image: mysql:5.6
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=db_password
      - MYSQL_DATABASE=joomla_ws
    networks:
      - web
    volumes:
      - database:/var/lib/mysql

networks:
  web:
    driver: bridge
volumes:
  joomla:
  database: